version: '3.1'

services:

   simepleweb:
       image: fils/goobjectweb:latest
       environment:
          - S3ADDRESS=
          - S3BUCKET=
          - S3PREFIX=
          - S3KEY=
          - S3SECRET=
       ports:
          - "8080:8080"
       networks:
          - web

networks:
   web:
      driver: overlay
